name: cuacfm
description: A radio station with radioco integration.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
      sdk: flutter
  flutter_localizations:
    sdk: flutter

  verbal_expressions: ^0.4.0
  audioplayers: '0.15.0'
  intl: ^0.16.1
  xml2json: ^4.3.0
  cupertino_icons: ^0.1.3
  device_info: ^0.4.2+6
  http: ^0.12.2
  html: ^0.14.0+3
  share: ^0.6.4+3
  shared_preferences: ^0.5.8
  injector: ^1.0.8
  animations: ^1.1.2
  cached_network_image: ^2.2.0+1
  flutter_html: ^1.0.2
  url_launcher: ^5.5.0
  font_awesome_flutter: ^8.8.1
  maps_launcher: ^1.2.2+1
  photo_view: ^0.10.0
  progress_indicators: ^0.1.5
  connectivity: ^0.4.9
  uuid: ^2.2.0
  provider: ^4.3.2
  firebase_core: ^0.4.5
  firebase_messaging: ^6.0.16
  firebase_performance: ^0.3.2
  firebase_crashlytics: ^0.1.4+1
  firebase_analytics: ^5.0.16
  firebase_in_app_messaging: ^0.1.2
  mock_web_server: ^4.1.1
  mockito: ^4.1.1
  countdown: ^0.1.0
  ozzie: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/graphics/icon_info.png
      - assets/graphics/play_podcast.png
      - assets/graphics/cuac-logo.png
      - assets/graphics/empty-logo.png
      - assets/graphics/categories/tv.jpeg
      - assets/graphics/categories/news.jpeg
      - assets/graphics/categories/sports.jpeg
      - assets/graphics/categories/society.jpeg
      - assets/graphics/categories/education.jpeg
      - assets/graphics/categories/comedy.jpeg
      - assets/graphics/categories/music.jpeg
      - assets/graphics/categories/science.jpeg
      - assets/graphics/categories/arts.jpeg
      - assets/graphics/categories/goverment.jpeg
      - assets/graphics/categories/health.jpeg
      - assets/graphics/categories/tech.jpeg
      - assets/graphics/faster.jpg
      - assets/graphics/sleep.jpg
      - assets/translations/en.json
      - assets/translations/es.json
      - assets/translations/gl.json
      - assets/translations/pt.json

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Light.ttf